import { ArrowRight, BookOpen, Lock, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";
import { RootState } from "../store/store";

export const DashboardHero = () => {
    const flashcards = useSelector((state: RootState) => state.flashcards.flashcards);

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            <div className="mb-10 text-center md:text-left">
                <h1 className="text-3xl font-bold text-zinc-900 tracking-tight">
                    Welcome back
                </h1>
                <p className="mt-2 text-zinc-500">
                    Track your learning progress and manage your knowledge base.
                </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Active Card: Flashcards Summary */}
                <div className="group relative bg-zinc-900 rounded-2xl p-8 shadow-xl hover:shadow-2xl transition-all duration-300 overflow-hidden">
                    <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity">
                        <BookOpen className="w-32 h-32 text-white" />
                    </div>

                    <div className="relative z-10 text-white">
                        <div className="inline-flex items-center justify-center p-3 bg-zinc-800 rounded-xl mb-6 border border-zinc-700">
                            <BookOpen className="w-6 h-6 text-white" />
                        </div>

                        <h2 className="text-2xl font-bold mb-2">My Flashcards</h2>
                        <div className="flex items-baseline gap-2 mb-6">
                            <span className="text-4xl font-extrabold">{flashcards.length}</span>
                            <span className="text-zinc-400 font-medium">cards created</span>
                        </div>

                        <p className="text-zinc-400 mb-8 max-w-sm">
                            Access your personalized collection of flashcards generated by Gemini AI.
                        </p>

                        <Link
                            to="/flashcards"
                            className="inline-flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-lg text-zinc-900 bg-white hover:bg-zinc-100 transition-colors shadow-sm"
                        >
                            Open Flashcards
                            <ArrowRight className="ml-2 w-4 h-4" />
                        </Link>
                    </div>
                </div>

                {/* Blurry "Coming Soon" Card */}
                <div className="relative bg-zinc-50 rounded-2xl p-8 border border-zinc-200 overflow-hidden">
                    {/* Overlay for blur/disable effect */}
                    <div className="absolute inset-0 bg-white/60 backdrop-blur-[2px] z-20 flex flex-col items-center justify-center">
                        <div className="bg-white p-4 rounded-full shadow-lg mb-4 ring-1 ring-zinc-100">
                            <Lock className="w-6 h-6 text-zinc-400" />
                        </div>
                        <h3 className="text-lg font-bold text-zinc-900">Coming Soon</h3>
                        <p className="text-zinc-500 text-sm">More study tools are on the way</p>
                    </div>

                    {/* Background content (blurred) */}
                    <div className="filter blur-sm select-none opacity-40">
                        <div className="inline-flex items-center justify-center p-3 bg-zinc-200 rounded-xl mb-6">
                            <Zap className="w-6 h-6 text-zinc-900" />
                        </div>
                        <h2 className="text-2xl font-bold text-zinc-900 mb-2">Smart Quiz</h2>
                        <div className="flex items-baseline gap-2 mb-6">
                            <span className="text-4xl font-extrabold text-zinc-900">0</span>
                            <span className="text-zinc-500 font-medium">completed</span>
                        </div>
                        <p className="text-zinc-500 mb-8 max-w-sm">
                            Test your knowledge with AI-generated quizzes based on your notes.
                        </p>
                        <button disabled className="inline-flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-lg text-white bg-zinc-900">
                            Start Quiz
                            <ArrowRight className="ml-2 w-4 h-4" />
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};
